Mydemy/Mydemy/urls.py
from django.conf.urls import url, include
from django.views.static import serve
import xadmin

from Mydemy.settings import MEDIA_ROOT
from users.views import LoginView, RegisterView, ActivateView, ForgetPwdView, ResetPwdView,\
    DoResetPwdView, LogOutView, HomeView


urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url('^$', HomeView.as_view(), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogOutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^active/(?P<verification_code>.*)/$', ActivateView.as_view(), name='active'),
    url(r'^forgetpwd/$', ForgetPwdView.as_view(), name='forget_pwd'),
    url(r'^resetpwd/(?P<verification_code>.*)/$', ResetPwdView.as_view(), name="reset_pwd"),
    url(r'^do_resetpwd/$', DoResetPwdView.as_view(), name='do_reset_pwd'),
    url(r'^org/', include(('organizations.urls', 'organizations'), namespace='org')),
    url(r'^course/', include(('courses.urls', 'courses'), namespace='course')),
    url(r'^user/', include(('users.urls', 'users'), namespace='user')),
    url(r'^media/(?P<path>.*)/$', serve, {'document_root': MEDIA_ROOT}),
    #url(r'^static/(?P<path>.*)/$', serve, {'document_root': STATIC_ROOT}),
    url(r'^ueditor/',include(('DjangoUeditor.urls', 'ueditor'), namespace='ueditor')),
]

handler404 = 'users.views.handler404'
handler500 = 'users.views.handler500'

Mydemy/apps/courses/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url


from .views import CourseListView, CourseOverviewView, CourseCommentsView, CourseVideoListView, CourseAddCommentView, VideoPlayView


urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name='list'),
    url(r'^overview/(?P<course_id>\d+)/$', CourseOverviewView.as_view(), name='overview'),
    url(r'^video_list/(?P<course_id>\d+)/$', CourseVideoListView.as_view(), name='video_list'),
    url(r'^comments/(?P<course_id>\d+)/$', CourseCommentsView.as_view(), name='comments'),
    url(r'^add_comment/$', CourseAddCommentView.as_view(), name='add_comment'),
    url(r'^video_play/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name='video_play'),
]

Mydemy/apps/organizations/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from organizations.views import OrgView, UserRequestView, OrgOverviewView, OrgInfoView, \
    OrgInstructorView, OrgCourseView, OrgFavView, InstructorListView, InstructorInfoView

urlpatterns = [
    url(r'^list/$', OrgView.as_view(), name='list'),
    url(r'^user_request/$', UserRequestView.as_view(), name='user_request'),
    url(r'^org_overview/(?P<org_id>\d+)/$', OrgOverviewView.as_view(), name='org_overview'),
    url(r'^org_info/(?P<org_id>\d+)/$', OrgInfoView.as_view(), name='org_info'),
    url(r'^org_instructor/(?P<org_id>\d+)/$', OrgInstructorView.as_view(), name='org_instructor'),
    url(r'^org_course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name='org_course'),
    url(r'^org_fav/$', OrgFavView.as_view(), name='org_fav'),

    url(r'^instructor/list/$', InstructorListView.as_view(), name='instructor_list'),
    url(r'^instructor/info/(?P<ins_id>\d+)/$', InstructorInfoView.as_view(), name='instructor_info'),
]

Mydemy/apps/users/urls.py
from django.conf.urls import url

from users.views import UserInfoView, UpdateUserPwdView, UpdateUserEmailView,UpdateUserAvatarView, \
    UpdateUserEmailGetVCView, UpdateUserProfileView, UserFavCourseView, UserFavInsView, UserFavOrgView, \
    UserCourseView, UserNotificationView


urlpatterns = [
    url(r'^info/$', UserInfoView.as_view(), name='info'),
    url(r'^update_avatar/', UpdateUserAvatarView.as_view(), name='update_avatar'),
    url(r'^update_pwd/$', UpdateUserPwdView.as_view(), name='update_pwd'),
    url(r'^update_email_vc/$', UpdateUserEmailGetVCView.as_view(), name='update_email_vc'),
    url(r'^update_email/$', UpdateUserEmailView.as_view(), name='update_email'),
    url(r'^update_user/$', UpdateUserProfileView.as_view(), name='update_user'),
    url(r'^fav_course/$', UserFavCourseView.as_view(), name='fav_course'),
    url(r'^fav_ins/$', UserFavInsView.as_view(), name='fav_ins'),
    url(r'^fav_org/$', UserFavOrgView.as_view(), name='fav_org'),
    url(r'^user_course/$', UserCourseView.as_view(), name='user_course'),
    url(r'^user_notification/$', UserNotificationView.as_view(), name='user_notification'),
]

Mydemy/plugins/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

Mydemy/apps/users/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms import ModelForm

from captcha.fields import CaptchaField

from .models import UserProfile, UserProfileVerification


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=6)


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True, initial='')
    password = forms.CharField(required=True, min_length=6, initial='')
    captcha = CaptchaField(error_messages=dict(
        invalid = 'Incorrect Captcha',
    ))


class ForgetPwdForm(forms.Form):
    email = forms.EmailField(required=True, initial='')
    captcha = CaptchaField(error_messages=dict(
        invalid = 'Incorrect Captcha',
    ))


class ResetPwdForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=6, initial='')
    password2 = forms.CharField(required=True, min_length=6, initial='')


class UpdateAvatarForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']


class EmailForm(ModelForm):
    class Meta:
        model = UserProfileVerification
        fields = ['email']


class UpdateEmailForm(ModelForm):
    class Meta:
        model = UserProfileVerification
        fields = ['email', 'code']


class UpdateUserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nickname', 'birthday', 'sex', 'address', 'mobile']

Mydemy/plugins/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

Mydemy/templates/course_detail_overview.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Course - Overview - Mydemy{% endblock %}

{% block crumbs %}
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="/">Main page</a>></li>
            <li><a href="{% url 'course:list' %}">Courses</a>></li>
            <li>Course Overview</li>
        </ul>
    </div>
{% endblock %}


{% block content %}
    <section>
        <div class="wp">
        <div class="groupPurchase_detail detail">
            <div class="toppro">
                <div class="left">
                    <div class="picbox">
                        <div class="tb-booth tb-pic">
                            <img width="440" height="445" src="{{ MEDIA_URL }}{{ course.image }}" class="jqzoom"/>
                        </div>
                    </div>
                    <div class="des">
                        <h1 title="{{ course.name }}">{{ course.name }}</h1>
                        <span class="key">{{ course.desc }}</span>
                        <div class="prize">
                            <span class="fl">Diffcuity: <i class="key">{{ course.difficulty }}</i></span>
                            <span class="fr">Students: {{ course.student_count }}</span>
                        </div>
                        <ul class="parameter">
                            <li><span class="pram word3">Duration：</span><span>{{ course.course_duration }} hours</span></li>
                            <li><span class="pram word3">Chapters：</span><span>{{ lesson_count }}</span></li>
                            <li><span class="pram word3">Category：</span><span title="">{{ course.category }}</span></li>
                            <li class="piclist"><span class="pram word4">Students：</span>
                                {% for user_course in course.getAllStudents %}
                                    <span class="pic"><img width="40" height="40" src="{{ MEDIA_URL }}{{ user_course.user.image }}"/></span>
                                {% endfor %}
                            </li>
                        </ul>
                        <div class="btns">
                            <div class="btn colectgroupbtn" id="jsLeftBtn">{% if fav_course %}Un-favorite{% else %}Favorite{% endif %}</div>
                            <div class="buy btn"><a style="color: white" href="{% url 'course:video_list' course.id %}">Go to Learn</a></div>
                        </div>
                    </div>

                </div>

                <div class="right">
                    <div class="head">
                        <h1>Organization</h1>
                    </div>
                    <div class="pic">
                        <a href="{% url 'org:org_overview' course.org.id %}">
                            <img width="150" height="80" src="{{ MEDIA_URL }}{{ course.org.image }}"/>
                        </a>
                    </div>
                    <a href="{% url 'org:org_overview' course.org.id %}">
                        <h2 class="center" title="{{ course.org.name }}">{{ course.org.name }}</h2>
                    </a>
                    <div class="btn  notlogin" data-favid="14" id="jsRightBtn">{% if fav_org %}Un-favorite{% else %}Favorite{% endif %}</div>
                    <div class="clear">
                        <ul>
                            <li>
                                <span>Courses: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ course.getAllLessons.count }}</span>
                            </li>
                            <li>
                                <span>Instructors:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ course.org.getAllInstructors.count }}</span>
                            </li>
                            <li>Location:&nbsp;&nbsp;{{ course.org.address }}</li>
                            <li>CERTIFICATED &nbsp;:
                                &nbsp;&nbsp;<img title="Certificate Provider" , src="{% static 'images/gold.png' %}"/>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
    <section>
        <div class="wp">
        <div class="list groupPurchase_detail_pro">
            <div class="left layout">
                <div class="head">
                    <ul class="tab_header">
                        <li class="active">Course Detail</li>
                    </ul>
                </div>
                <div class="tab_cont tab_cont1">
                    {% autoescape off %}
                        {{ course.detail }}
                    {% endautoescape %}
                </div>
                <div class="tab_cont tab_cont2">
                    <div class="comment">
                        <div class="comenlist">
                        </div>
                    </div>
                </div>
            </div>
            <div class="right layout">
                <div class="head">Related Courses</div>
                    {% if relate_courses %}
                        {% for relate_course in relate_courses %}
                            <dl>
                                <dt>
                                    <a target="_blank" href="">
                                        <img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ relate_course.image }}"/>
                                    </a>
                                </dt>
                                <dd>
                                    <a target="_blank" href=""><h2> {{ relate_course.name }}</h2></a>
                                    <span class="fl">Duration：<i class="key">{{ relate_course.course_duration}}</i></span>
                                </dd>
                            </dl>
                        {% endfor %}
                    {% endif %}
            </div>
        </div>
    </div>
    </section>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        function add_fav(current_elem, fav_id, fav_type) {
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'org:org_fav' %}",
                data: {'fav_id': fav_id, 'fav_type': fav_type},
                async: true,
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                    if (data.status == 'fail') {
                        if (data.msg == 'Login Required') {
                            window.location.href = "{% url 'login' %}";
                        } else {
                            alert(data.msg);
                        }
                    } else if (data.status == 'success') {
                        current_elem.text(data.msg);
                    }
                }
            });
        }

        $('#jsLeftBtn').on('click', function () {
            add_fav($(this), {{ course.id }}, 2);
        });

        $('#jsRightBtn').on('click', function () {
            add_fav($(this), {{ course.org.id }}, 3);
        });
    </script>
{% endblock %}

Mydemy/templates/org_detail_course.html
{% extends 'org_base.html' %}

{% load staticfiles %}

{% block title %}Organization - Course - Mydemy{% endblock %}

{% block crumbs %}
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="/">Main page</a>></li>
            <li><a href="{% url 'org:list' %}">Organization</a>></li>
            <li>Course Information</li>
        </ul>
    </div>
{% endblock %}

{% block left_org_page %}
    <div class="left">
        <ul>
            <li><a href="{% url 'org:org_overview' org.id %}">Organization</a></li>
            <li class="active2"><a>Course</a></li>
            <li><a href="{% url 'org:org_info' org.id %}">Organization</a></li>
            <li><a href="{% url 'org:org_instructor' org.id %}">Instructor</a></li>
        </ul>
    </div>
{% endblock %}

{% block right_org_page %}
    <div class="right companycenter layout" >
		<div class="head">
			<h1>Courses</h1>
		</div>
        {% if org_courses %}
            <div class="brief group_list">
            {% for course in org_courses %}
                <div class="module1_5 box">
                    <a class="comp-img-box" href="/group/groupdetail/13/">
                        <img width="214" height="195" src="{{ MEDIA_URL }}{{ course.image }}"/>
                    </a>
                    <div class="des">
                        <a href="/group/groupdetail/13/"><h2>{{ course.name }}</h2></a>
                        <span class="fl">Duration:<i class="key">{{ course.course_duration }}</i></span>
                        <span class="fr">Students:<i class="key">{{ course.student_count }}</i></span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ course.org.name }}</span>
                         <span class="star fr  notlogin" data-favid="13" data-fav-type="4">{{ course.fav_count }}</span>
                    </div>
                </div>
            {% endfor %}
            </div>
        {% endif %}
        <div class="pageturn">
            <ul class="pagelist">
                <li class="active"><a href="?page=1">1 PAGATION HERE</a></li>
            </ul>
        </div>
	</div>
{% endblock %}

Mydemy/templates/user_fav_instructor.html
{% extends 'user_base.html' %}

{% load staticfiles %}

{% block title %} Favorite Instructors - {{ request.user.nickname }}{% endblock %}

{% block crumbs %}
	<div class="wp">
		<ul  class="crumbs">
			<li><a href="/">Main</a>></li>
            <li><a href="/">User</a>></li>
            <li>User Information</li>
		</ul>
	</div>
{% endblock crumbs %}

{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>Favorite</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'user:fav_org' %}">Organizations</a></li>
                        <li class="active"><a href="{% url 'user:fav_ins' %}">Instructors</a></li>
                        <li><a href="{% url 'user:fav_course' %}">Courses</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for instructor in instructors %}
                        <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="{% url 'org:instructor_info' instructor.id %}">
                                    <img width="100" height="100" class="scrollLoading" src="{{ MEDIA_URL }}{{ instructor.avatar }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="{% url 'org:instructor_info' instructor.id %}">
                                        {{ instructor.name }}<span class="key">Verified</span>
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">Years of Experience: <span>{{ instructor.work_year }}</span></li>
                                    <li class="c7">Courses: <span>{{ instructor.get_course_count }}</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">Company: <span>{{ instructor.curr_company }}</span></li>
                                    <li class="c7">Position: <span>{{ instructor.curr_title }}</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav" fav-id="{{ instructor.id }}"></div>
                        </dl>
                    </div>
                    {% endfor%}
                </div>
            </div>
        </div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        $('.jsDeleteFav').on('click', function () {
            add_fav($(this), $( this ).attr( "fav-id" ), 1, "{% url 'org:org_fav' %}", "{{ csrf_token }}");
        });
    </script>
{% endblock %}

Mydemy/templates/user_fav_org.html
{% extends 'user_base.html' %}

{% load staticfiles %}

{% block title %} Favorite Organizations - {{ request.user.nickname }}{% endblock %}

{% block crumbs %}
	<div class="wp">
		<ul  class="crumbs">
			<li><a href="/">Main</a>></li>
            <li><a href="/">User</a>></li>
            <li>User Information</li>
		</ul>
	</div>
{% endblock crumbs %}

{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>Favorite</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'user:fav_org' %}">Organizations</a></li>
                        <li ><a href="{% url 'user:fav_ins' %}">Instructors</a></li>
                        <li><a href="{% url 'user:fav_course' %}">Courses</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in orgs %}
                        <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_overview' org.id %}">
                                    <img width="160" height="90" class="scrollLoading" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:org_overview' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">
                                    <img src="{% static 'images/authentication.png' %}"/>
                                    <img src="{% static 'images/gold.png' %}"/>
                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav" fav-id="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        $('.jsDeleteFav').on('click', function () {
            add_fav($(this), $( this ).attr( "fav-id" ), 3, "{% url 'org:org_fav' %}", "{{ csrf_token }}");
        });
    </script>
{% endblock %}